services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: poetry run python src/main.py

  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app-network

  ollama:
    build: ./ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - app-network
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL}

networks:
  app-network:


volumes:
  ollama:
