services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./data/texts:/app/data/texts
    depends_on:
      - ollama
    networks:
      - app-network
    environment:
      - OLLAMA_URL=http://ollama:11434

  web:
    build: ./web
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - app-network

  ollama:
    build: ./ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - app-network
    entrypoint: /usr/local/bin/download_model.sh

networks:
  app-network:


volumes:
  ollama:
