[tool.poetry]
name = "baby-ai-api"
version = "0.1.0"
description = ""
authors = ["Jo Kroese <jo@jokroese.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9, <3.12"
langchain = "^0.1.13"
langchain-openai = "^0.1.1"
beautifulsoup4 = "^4.12.3"
faiss-cpu = "^1.8.0"
langserve = {extras = ["all"], version = "^0.0.51"}
langchainhub = "^0.1.15"
pandoc = "^2.3"
unstructured = "^0.12.6"
pypandoc = "^1.13"
markdown = "^3.6"
langchain-ai21 = "^0.1.2"
llama-index = "^0.10.25"
llama-index-llms-ollama = "^0.1.2"
chromadb = "^0.4.24"
hdbscan = "^0.8.33"
tqdm = "^4.66.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
