[tool.poetry]
name = "baby-ai-api"
version = "0.1.0"
description = ""
authors = ["Jo Kroese <jo@jokroese.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9, <3.12"
langchain = "^0.1.13"
faiss-cpu = "^1.8.0"
langserve = {extras = ["all"], version = "^0.0.51"}
langchainhub = "^0.1.15"
unstructured = {extras = ["pdf"], version = "^0.13.2"}
langchain-ai21 = "^0.1.2"
llama-index = "^0.10.25"
llama-index-llms-ollama = "^0.1.2"
tqdm = "^4.66.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
